### ISSUE TITLE
Inspec-1.51.* fail with --concurrency option in kitchen

### ISSUE THREAD

**Issue by Linutux42** [inspec/kitchen-inspec#167]
Hello,

I just found out a bug and I am not sure if the issue is within kitchen-inspec or inspec itself.
When I use --concurrency option while doing kitchen verify I get the following error:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `each' for nil:NilClass] on test-cookbook-centos-7-x86-64
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

If I remove the --concurrency option the kitchen verify finishes without issue.
I got the same result on two dinstinct servers and even on my workstation.

Here are the version I tried:
- kitchen-inspec: 0.22.0, 0.20.0
- inspec: 1.51.*

It works with inspec-1.49.2 though.

I could not test it with inspec-2.* because I have the following issue, even though I have inspec-2.0.17 installed. Should I open another issue about that or is it an issue on my end only ?
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'inspec' verifier from the load path. Please ensure that your transport is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Let me know if you need any more informations

Thanks

**Comment by cheeseplus** [comment]
The first error we would need some more context, namely the .kitchen.yml and the concurrency value passed (ideally the actual command). The latter failure means that whatever kitchen binary you are using can't see kitchen-inspec, this is probably a local environment condition - i.e. ChefDK not installed correctly or something not set correctly in the .kitchen.yml.

**Comment by Linutux42** [comment]
Hey @cheeseplus,

1st error:
- Any value superior to 1 ended up with this issue. I tried from 1 to 10.
- Command : 
`$> kitchen verify --concurency 10`

.kitchen.yml:
```
---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 1
    natnet1: "192.168/16"
  boot_timeout: 3600

transport:
  name: sftp

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  chef_omnibus_url: http://chef-omnibus.ubisoft.org

verifier:
  name: inspec

platforms:
- name: centos-6-x86_64
  driver:
    box: centos-6-x86_64
    box_url: http://repository/vagrant-boxes/centos-6-x86_64.box
    box_check_update: true

- name: centos-7-x86_64
  driver:
    box: centos-7-x86_64
    box_url: http://repository/vagrant-boxes/centos-7-x86_64.box
    box_check_update: true

suites:
- name: test_cookbook
  data_bags_path: ../data_bags/
  run_list:
    - recipe[test_cookbook::default]
  verifier:
    inspec_tests:
      - test/basic/default.rb
```

I'll check the second error later :)

Thank you,
Maxence
