### ISSUE TITLE
Private Supermarket call which uses bitbucket verify action: [not in gzip format]

### ISSUE THREAD

**Issue by timusmc96** [inspec/kitchen-inspec#178]
Setup kitchen.yml with the following, but not able to get profile

```yaml
verifier:
 inspec_tests:
 - name: linux-hardening
   supermarket: som3guy/apache-disa-stig
   supermarket_url: https://my.supermarket.com
```
All profiles are setup and stored in bitbucket.   I see no issue if I use, -git: <url>, but we really want to pull profiles from our private supermarket.

Thanks
