### ISSUE TITLE
Question regarding verifier settings

### ISSUE THREAD

**Issue by paulcalabro** [inspec/kitchen-inspec#206]
Hi,

Will the latest tagged release support the new verifier settings provided in the docs:

```
verifier:
  name: inspec
  format: junit
  output: path/to/results/%{platform}_%{suite}_inspec.xml
```

Thanks,
Paul

**Comment by paulcalabro** [comment]
p.s. The reason why I ask is that we need to use a pinned version of the gem and last I checked that version did not support it. I could be wrong though.

**Comment by wiebe** [comment]
Just try it out?

You could also choose to pin it to the latest development version until a new tagged version will get release. It supports the new reporter option which also allows multiple reporters/outputs, so for example junit + commandline.

```
gem 'kitchen-inspec', :git => 'https://github.com/inspec/kitchen-inspec.git', :ref => '09976b4'
```  

```
verifier:
  name: inspec
  reporter:
    - cli 
    - junit:path/to/results/%{platform}_%{suite}_inspec.xml
```
