### ISSUE TITLE
Reporter failures with kitchen 1.24.0 and kitchen-inspec 1.0.1

### ISSUE THREAD

**Issue by larkinc** [inspec/kitchen-inspec#222]
Kitchen yaml has:
```
verifier:
  name: inspec
  reporter: documentation
```

When you run `kitchen verify` you get:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `map' for "documentation":String
Did you mean?  tap] on suite
>>>>>> ----------------------
```

Kitchen yaml has:
```
verifier:
  name: inspec
  reporter: progress
```

When you run `kitchen verify` you get:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `map' for "progress":String
Did you mean?  tap] on suite
>>>>>> ----------------------
```

This is still working.  Kitchen yaml has:
```
verifier:
  name: inspec
  reporter:
    - json:.kitchen/test/results/%{platform}_%{suite}_inspec.json
```
