### ISSUE TITLE
Inputs are not passed to InSpec during kitchen verify

### ISSUE THREAD

**Issue by russellseymour** [inspec/kitchen-inspec#237]
# Version:

1.1.0

# Environment:

Target machine is Ubuntu 18.04 with Chef 15 being installed
Machine running Test Kitchen is Windows 10

# Scenario:

I am trying to set inputs in the `kitchen.yml` file thus:

```yaml
    verifier:
      inspec_tests:
        - path: test/integration/camsa
      inputs:
        username: <%= ENV['CAMSA_USERNAME'] || 'foobar' %>
        managed_app: <%= ENV['MANAGED_APP'] || false %>
        automate_fqdn: <%= ENV['AUTOMATE_FQDN'] || 'tk-automate.managedautomate.io' %>
        customer_name: <%=
          firstname = ENV['CAMSA_FIRSTNAME'] || 'Foo'
          lastname = ENV['CAMSA_LASTNAME'] || 'Bar'
          '%s %s' % [firstname, lastname]
        %>   
```

However when the tests run they do not get these values.

When I run `kitchen diagnose --all` I can see that the verifier section has values, it appears that they are not respected by inspec.

```
verifier:
  chef_omnibus_root: "/opt/chef"
  command_prefix:
  debug:
  ftp_proxy:
  http_proxy:
  https_proxy:
  inputs:
    username: foobar
    managed_app: false
    automate_fqdn: tk-automate.managedautomate.io
    customer_name: Foo Bar
  inspec_tests:
  - path: test/integration/camsa
```

# Steps to Reproduce:

Set input values in Test Kitchen and run a test similar to the following

```ruby
customer_name = input('customer_name', value: '')

# Check that the license has been applied properly and registered with the correct user
cmd = 'curl https://127.0.0.1/api/v0/license/status -k --cert /hab/svc/deployment-service/data/deployment-service.crt --key /hab/svc/deployment-service/data/deployment-service.key --cacert /hab/svc/deployment-service/data/root.crt'
describe json({command: cmd}) do
  its ('customer_name') { should include customer_name }
end
```

# Expected Result:

The `customer_name` should be populated with "Foo Bar"

# Actual Result:

The output of this test shows that `customer_name` is still blank

```
  JSON from command: curl https://127.0.0.1/api/v0/license/status -k --cert /hab/svc/deployment-service/data/deployment-service.crt --key /hab/svc/deployment-service/data/deployment-service.key --cacert /hab/svc/deployment-service/data/root.crt
     [PASS]  customer_name should include ""
```
