### ISSUE TITLE
uninitialised constant Kitchen::Verifier::Inspec::Hashie when declaring inputs

### ISSUE THREAD

**Issue by walterdolce** [inspec/kitchen-inspec#242]
# Version:
```
# Gemfile
source 'https://rubygems.org'

gem 'kitchen-ansible', '0.48.8'
gem 'kitchen-inspec', '1.2.0'
gem 'kitchen-vagrant', '1.3.4'
gem 'inspec-bin', '4.17.17'
```

# Environment:
macOS

# Scenario:
Trying to run `bundle exec kitchen verify`

# Steps to Reproduce:
Create a `.kitchen.yml` and add the following bits to it:
```
verifier:
  name: inspec
  inputs:
    # make this an attribute required by one of the inspec tests below
    foo: bar
  inspec_tests:
  - path: ./path/to/some/inspec/tests

platforms:
  - name: ubuntu-16.04
    box: bento/ubuntu-16.04
    box_version: 201808.24.0

suites:
  - name: default
```

# Expected Result:
test-kitchen fires the inspec verifier as normal (doesn't matter whether the tests pass or not)

# Actual Result:
```
-----> Starting Kitchen (v1.25.0)
-----> Verifying <default-ubuntu-1604>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [uninitialized constant Kitchen::Verifier::Inspec::Hashie] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

[What actually happens after the reproduction steps?]
❓ 

Note: by commenting out the `inputs` section, the problem goes away. I can run inspec normally.
